### ISSUE TITLE
Can't find module [ta]

### ISSUE THREAD

**Issue by p3i0t** [dolphindb/Tutorials_CN#12]
I tried the following lines in the dolphindb command line after running `./dolphindb`. However, it reports the error "Can't find module [ta]". Seems that the `ta` module is not included in zip file.  Is the `ta` module opensourced?

**Comment by ShenaMao** [comment]
> I tried the following lines in the dolphindb command line after running `./dolphindb`. However, it reports the error "Can't find module [ta]". Seems that the `ta` module is not included in zip file. Is the `ta` module opensourced?

Yes, it is. You could find it through https://github.com/dolphindb/DolphinDBModules
