### ISSUE TITLE
究竟有多少种表？文档存在误导或模糊

### ISSUE THREAD

**Issue by bigreybear** [dolphindb/Tutorials_CN#19]
浅谈 4 点，可以主要看 1-3。

1. 比如关于[数据形式](https://www.dolphindb.cn/cn/help/130/DataTypesandStructures/DataForms/index.html)的介绍里，将 [createPartitionedTable](https://www.dolphindb.cn/cn/help/130/FunctionsandCommands/FunctionReferences/c/createPartitionedTable.html) 称为“分布式表” 就根本错误，因为分区表的页面显示，可以创建在本次磁盘、分布式系统或内存中。

![image](https://github.com/dolphindb/Tutorials_CN/assets/22140148/f5e6a93a-9f30-4a77-97c0-007524eff9e5)

2. **维度表和分布式表不是平行关系，是包含关系**。下图中，“维度表”和“分布式表”被如此提及，让人感觉维度表既不是内存表，也不是分布式表。而实际从[维度表的介绍](https://www.dolphindb.cn/cn/help/200/FunctionsandCommands/FunctionReferences/c/createTable.html#createtable)中，可以发现维度表只能是分布式表。

![image](https://github.com/dolphindb/Tutorials_CN/assets/22140148/5f4aa0f0-67f2-4e94-8238-23f9a39346dd)

3. **关键定义混乱或冗余**。比如冗余：排序列/索引列对于分区表其实很重要，但是如下介绍中 定义了一个 `sort key entry`，但是后文**再也没有使用过这个概念**，都是在说 `sort key 组合值/数`，**那定义这个`entry`做什么呢**？；比如混乱：这里涉及到两个关键概念：`sort key`， `排序列`，两者的关系没有明确的说明，需要读者去推导才能知道“sort key 是不包含自动添加的时间戳列的排序列”（姑且认为是这样）。而且`sort key`从上下文看译名居然是“索引列”，恰恰直译的“排序列”又是另一个概念，**为什么要使用如此容易混淆的术语呢**？

![image](https://github.com/dolphindb/Tutorials_CN/assets/22140148/1b112659-e8dc-4e7b-b98b-90842dc80210)

4. 对于可能相同的内容复制粘贴，导致概念混淆。比如维度表和分区表都要有 sortColumn，但是维度表没有分区啊，结果如下维度表介绍中有提到了分区概念。

![image](https://github.com/dolphindb/Tutorials_CN/assets/22140148/bafee240-3414-4aa8-93da-8d2e6f7ad7d6)

**Comment by hzwale** [comment]
非常感谢您的建议，我们会在内部讨论后，在未来版本中进行内容优化和调整。

**Comment by bigreybear** [comment]
@peeyee hello is these all completed? I didnt see it from current official doc on website
