### ISSUE TITLE
src/central_freelist.cc:330] tcmalloc: allocation failed 8192

### ISSUE THREAD

**Issue by linsamtw** [dolphindb/Tutorials_CN#22]
如題，我用的是社群版本，經常發生
`src/central_freelist.cc:330] tcmalloc: allocation failed 8192`
想問是我記憶體問題嗎?

我用的版本是，`DolphinDB_Linux64_V1.20.5`

**Comment by peeyee** [comment]
社区版每个节点（即进程）限制 2Cores ， 8GB的资源使用。
您的场景时内存到顶8G上限了，请优化下程序内存使用量。

**Comment by linsamtw** [comment]
不好意思，想做個確認
dolphindb 內建不會控制 memory usage，但只要超過 8GB，會直接 raise error，對嗎?

**Comment by linsamtw** [comment]
dolphindb 會先將 data cache 到 memory
那想問，要如何清空 memory，將沒用到的 data clear 呢?

**Comment by peeyee** [comment]
可以参考此教程：https://github.com/dolphindb/Tutorials_CN/blob/master/memory_management.md
清理内存
