### ISSUE TITLE
如何把，日資料，轉換成週K、月K?

### ISSUE THREAD

**Issue by linsamtw** [dolphindb/Tutorials_CN#25]
如何把，日資料，轉換成週K、月K?

**Comment by ffliu29** [comment]
批计算的话可以用 SQL 语句实现，select ...(聚合计算) from t group by bar / dailyAlignedBar / Interval 函数
实时计算可以用时序聚合引擎，参考文档 
https://docs.dolphindb.cn/zh/funcs/c/createTimeSeriesEngine.html https://docs.dolphindb.cn/zh/funcs/c/createDailyTimeSeriesEngine.html

**Comment by ffliu29** [comment]
此外我们内部也提供了一篇教程可供参考
基于快照行情的股票和基金 K 线合成 https://docs.dolphindb.cn/zh/tutorials/k.html
