### ISSUE TITLE
Partition size should not be too small

### ISSUE THREAD

**Issue by linsamtw** [dolphindb/Tutorials_CN#27]
# overview

在英文版文件中，4.3 寫到 
- [4.3 Partition size should not be too small](https://github.com/dolphindb/Tutorials_EN/blob/master/database.md#43-partition-size-should-not-be-too-small)

針對 4.3 的狀況，可以提供一個，建立 partition 的例子嗎? 謝謝

**Comment by peeyee** [comment]
https://docs.dolphindb.cn/zh/tutorials/best_practices_for_partitioned_storage.html
