### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by windancer79** [dolphindb/Tutorials_CN#3]
在按照docker部署教程步骤，到执行docker-compose up -d 遇到以下问题：

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by huzhiying** [comment]
把./docker-compose.yml中的version改为"2"即可。
