### ISSUE TITLE
组合 (COMPO) 分区列可以使用 HASH 分区

### ISSUE THREAD

**Issue by cyfdecyf** [dolphindb/Tutorials_CN#5]
[组合 (COMPO) 分区](https://github.com/dolphindb/Tutorials_CN/blob/master/database.md#36-%E7%BB%84%E5%90%88compo%E5%88%86%E5%8C%BA) 实测在 1.10.11 版本中可以使用 HASH 分区作为分区列，文档中遗漏了这一类型。

**Comment by xiaodanzhang** [comment]
非常感谢您的宝贵建议！已经修复！https://github.com/dolphindb/Tutorials_CN/blob/master/database.md
