### ISSUE TITLE
PartitionedTable 支援 unique key 嗎?

### ISSUE THREAD

**Issue by linsamtw** [dolphindb/Tutorials_CN#6]
請問 PartitionedTable ( dfs ) 支援 unique key 嗎?

或是 dolphindb 有其他方法，避免重複的 data insert

in-memory table with primary key，
memory table 可以透過設定 primary key 避免重複 data

不知 dfs 的 table 是否有類似功能? 

謝謝

**Comment by xiaodanzhang** [comment]
您好！
DolphinDB目前dfs table不支援uniq key. 沒有直接方法實現uniq key。這主要由於dfs table壹般存放非常大的數據集，去重的cost非常高。

不過，如果不是全庫去重，可以通過訂閱過濾的方法（https://github.com/dolphindb/Tutorials_CN/blob/master/streaming_tutorial.md）；
或者通過可以通過先寫入keyedTable,再寫入dfs；
 
**我們通常建議，在查詢的時候來去重**， 例如：
**select top 1 * from t context by a,b,c**
通過這種方法，不用像group by壹樣，來做聚合運算，所以效率非常高。
