### ISSUE TITLE
是否可以同時 insert ?

### ISSUE THREAD

**Issue by linsamtw** [dolphindb/Tutorials_CN#7]
在同時 insert db 時，出現這個 error

RuntimeError: <Server Exception> in run: <ChunkInTransaction>filepath 'xxx/xxx/20051013' has been owned by transaction 4717

是否可以同時 insert ?

    n=1000000
    ID=rand(10, n)
    x=rand(1.0, n)
    t=table(ID, x)
    db=database("dfs://rangedb", RANGE,  0 5 10)
    pt=db.createPartitionedTable(t, `pt, `ID)
    pt.append!(t);

----------------------------------

另外，如果不能同時 insert，有沒有 function，可以判斷，DB 是否被 lock 住

**Comment by xiaodanzhang** [comment]
可以同時insert,但是需要insert到不同的分區，例如一個insert 到 0~5, 一個insert到5~10. 同一個分區不能有多於一個進程寫入。

**Comment by linsamtw** [comment]
> 可以同時insert,但是需要insert到不同的分區，例如一個insert 到 0~5, 一個insert到5~10. 同一個分區不能有多於一個進程寫入。

那有沒有 function 可以判斷，該 table 正在被寫入?  這樣比較好避免同時 insert

**Comment by xiaodanzhang** [comment]
没有这样的function; 不过可以通过查询记录变化来check是否有写入。
